The fitness of an initial clone is defined using the `fitness_array`.  

If `fitness_array` is defined, it must contain a fitness value for each unique initial clone.   
If no `fitness_array` is provided, all initial clones will be given a fitness value of 1.  

-----

The fitness of mutations that are generated during a simulation is more complex, and described in other tutorial notebooks.

In [1]:
%matplotlib inline
import numpy as np

In [2]:
from clone_competition_simulation import Parameters

In [4]:
p = Parameters(algorithm='Moran', initial_size_array=np.ones(16), print_warnings=False)
s = p.get_simulator()
s.run_sim()
s.view_clone_info()
# With no fitness defined, all of the clones are given a fitness of 1

    clone id  label  ...  parent clone id  last gene mutated
0          0      0  ...               -1               None
1          1      0  ...               -1               None
2          2      0  ...               -1               None
3          3      0  ...               -1               None
4          4      0  ...               -1               None
5          5      0  ...               -1               None
6          6      0  ...               -1               None
7          7      0  ...               -1               None
8          8      0  ...               -1               None
9          9      0  ...               -1               None
10        10      0  ...               -1               None
11        11      0  ...               -1               None
12        12      0  ...               -1               None
13        13      0  ...               -1               None
14        14      0  ...               -1               None
15        15      0  ...               -1               None

[16 rows x 6 columns]

In [7]:
# Given each initial clone a random fitness value between 0.5 and 1.5
p = Parameters(algorithm='Moran', initial_size_array=np.ones(16), 
               fitness_array=np.random.uniform(0.5, 1.5, size=16), 
               print_warnings=False)
s = p.get_simulator()
s.run_sim()
s.view_clone_info()

    clone id  label  ...  parent clone id  last gene mutated
0          0      0  ...               -1               None
1          1      0  ...               -1               None
2          2      0  ...               -1               None
3          3      0  ...               -1               None
4          4      0  ...               -1               None
5          5      0  ...               -1               None
6          6      0  ...               -1               None
7          7      0  ...               -1               None
8          8      0  ...               -1               None
9          9      0  ...               -1               None
10        10      0  ...               -1               None
11        11      0  ...               -1               None
12        12      0  ...               -1               None
13        13      0  ...               -1               None
14        14      0  ...               -1               None
15        15      0  ...               -1               None

[16 rows x 6 columns]

In [10]:
# The same principle works for clones defined using a grid
p = Parameters(algorithm='Moran2D', initial_grid=np.arange(16).reshape(4, 4), 
               fitness_array=np.random.uniform(0.5, 1.5, size=16), 
               print_warnings=False)
s = p.get_simulator()
s.run_sim()
s.view_clone_info()

    clone id  label  ...  parent clone id  last gene mutated
0          0      0  ...               -1               None
1          1      0  ...               -1               None
2          2      0  ...               -1               None
3          3      0  ...               -1               None
4          4      0  ...               -1               None
5          5      0  ...               -1               None
6          6      0  ...               -1               None
7          7      0  ...               -1               None
8          8      0  ...               -1               None
9          9      0  ...               -1               None
10        10      0  ...               -1               None
11        11      0  ...               -1               None
12        12      0  ...               -1               None
13        13      0  ...               -1               None
14        14      0  ...               -1               None
15        15      0  ...               -1               None

[16 rows x 6 columns]